### ISSUE TITLE
Dockerfile and upgrade

### ISSUE THREAD

**Issue by chatch** [ethereum/oyente#7]
Can you add the Dockerfile for https://hub.docker.com/r/hrishioa/oyente/ to the repo?  Link it on docker hub too if possible.

I'd like to make some changes to it.

**Comment by hrishioa** [comment]
Added Dockerfile to root of repo. This is a functional dockerfile as of now, some modifications were made (disasm is no longer available from the ethereum PPA, needs to be compiled manually) which may deviate from the image currently on Docker Hub.

**Comment by loiluu** [comment]
This issue was moved to melonproject/oyente#7
